In [4]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr)
# Array Operations(vectoration)
print(arr*2)

print(arr1+arr2)
# Reshaping
arr3=np.arange(12).reshape(3,4)
print(arr3)
# Matrix operatioons
matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
print(np.dot(matrix1,matrix2))
# Statistical operations
data=np.random.normal(0,1,1000)
print(f"Mean:{data.mean()},Std:{data.std()}")

[1 2 3]
[2 4 6]
[5 7 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[19 22]
 [43 50]]
Mean:-0.06316538726536598,Std:1.046212071061688


In [12]:
import pandas as pd
import numpy as np

data={
    'Name':['Alice','Bob','Charlie','David'],
    'Age':[25,30,35,40],
    'Salary':[5000,60000,70000,800000]
}

df=pd.DataFrame(data)
print(df)

print(df.head(2))
print(df.describe())
print(df['Age'].mean())

# data selec
print(df[df['Age']>30])
print(df.loc[1:2,['Name','Salary']])

# handling missing data
df_with_nan=pd.DataFrame({
    'A':[1,2,np.nan,4],
    'B':[5,np.nan,np.nan,8]
})
print(df_with_nan.fillna(value=0))
print(df_with_nan.dropna())
                  

      Name  Age  Salary
0    Alice   25    5000
1      Bob   30   60000
2  Charlie   35   70000
3    David   40  800000
    Name  Age  Salary
0  Alice   25    5000
1    Bob   30   60000
             Age         Salary
count   4.000000       4.000000
mean   32.500000  233750.000000
std     6.454972  378580.132425
min    25.000000    5000.000000
25%    28.750000   46250.000000
50%    32.500000   65000.000000
75%    36.250000  252500.000000
max    40.000000  800000.000000
32.5
      Name  Age  Salary
2  Charlie   35   70000
3    David   40  800000
      Name  Salary
1      Bob   60000
2  Charlie   70000
     A    B
0  1.0  5.0
1  2.0  0.0
2  0.0  0.0
3  4.0  8.0
     A    B
0  1.0  5.0
3  4.0  8.0
